---
title: "Analysis of Physical Activity Survey(2022)"
author: 
  - Jonathan Goodwin
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Water source and availability are important factors in determining the health and safety of a society. We obtain data regarding the activity of individuals of different states and age groups as well as their respective distance to a park. We find that citizens who live closer to parks are more likely to be physically active, and that younger citizens are more likely to be physically active then older ones. These findings have implications for the future development of public recreational structures."
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---
```{r setup, include=FALSE,warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message= FALSE, fig.pos = 'H')
library(tidyverse)
library(kableExtra)
library(reshape2)
```

# Introduction {#Intro}

 Physical activity is an important indicator for the health of the population of the United States. As well living near to a public recreational service like a park allows residents a more convenient place to excercise. We see that decreasing the distance to a park as well as giving more opportunity for residents to participate in activities like biking is associated with more physically active residents who meet the CDC's guidelines for strength and aerobic health.

  We analyzed the sources of water for two subsets of the Jordan population, urban and rural residents. From Figure ###Reference### and Figure ###Reference###, we can see that both California is the state with the most active populace, and that New York is the state where residents most commonly walk and/or bike to work. We also see that more rural states like Nebraska and Alaska have the fewest people living near a park.

  This information is relevant to the further development and enhancement of the recreational and physical activity of citizens of the United States as well as leader of respective states when developing cities. The data can help to identify populaces with particularly low activity reletive to the rest of the country as well as identify states that are lacking in public recreational support for its citizens.

  In section \@ref(Data) we talk about the process of gathering and analyzing the dataset and the variables. Then in section \@ref(Results) we discuss the implications of the dataset presented. Finally in section \@ref(Discussion) we discuss implications for the United States citizens, as well as the weakness of the study and the further investigation that may be useful to the topic of recreational activity support and physical activity in the United States.

\newpage

# Data {#Data}


# Results {#Results}


# Discussion {#Discussion}

## FirstPoint {#FirstPoint}



## Weaknesses and next steps


\newpage

\appendix

# Appendix {-}

## DataSheet {-}


## Code {-}

Repository associated with this analysis is available at [github](https://github.com/Jon-Goodwin/Final)

\newpage


# References